--liquibase formatted sql

--changeset tsuprenko:1
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(255) NOT NULL,
    amount DECIMAL(38, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    next_payment_date DATE
);
